name: CI/CD

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: vps
      url: ${{ vars.URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
        with:
          source: "."
          target: ${{ secrets.TARGET_FOLDER }}
      - name: Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSWORD }}
          script: cd ${{ secrets.TARGET_FOLDER }} && ./deploy.sh