name: CI/CD

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: vps
      url: ${{ vars.URL }}
    runs-on: vps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy script
        env:
          target_folder: ${{ secrets.TARGET_FOLDER }}
        run: ./deploy.sh